name : Deploy React APP

on:
  push:
    branches:
      - main
    
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Deploy to Render
        run:
          curl -X POST ${{ secrets.RENDER_DEPLOYMENT_HOOK_URL }}
          ## Open the render -> settings -> deploy hook-> copy url 
          ## Open github -> settings -> secrets and variables -> actions -> new repository secret -> add the url as RENDER_DEPLOY_HOOK_URL




